spring:
  cache:
    type: redis
  cache-null-values: true
  datasource:
    url: jdbc:h2:mem:moviedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      hbm2ddl:
        auto: update
      ddl-auto: update
  h2:
    console:
      enabled: true




